### ISSUE TITLE
Convert to multi module project

### ISSUE THREAD

**Issue by zesch** [Horsmann/ltlab-evaluation#1]
We should probably have a multi-module project as we might draw in some additional dependencies.

**Comment by Horsmann** [comment]
which structure do you have in mind?

**Comment by zesch** [comment]
TBD next time?
Or should we do that before?

**Comment by Horsmann** [comment]
I think I would like this to be happen before #7 
At least we should ensure that the group-id does not change any further and `*ltl.evaluation` remains the top-level name of our project

**Comment by zesch** [comment]
Not now :)
