### ISSUE TITLE
First release: 0.1.1

### ISSUE THREAD

**Issue by zesch** [Horsmann/ltlab-evaluation#7]
We should prepare everything to make a early first release, so that we can have quick release cycles.

**Comment by Horsmann** [comment]
Shouldn't be that much work at the actual code base. Who is going to release? Me? Someone else? 

- [ ] We will have to request a  new project at sonatype which might take 1-2 days. Is the current project name (`de.unidue.ltl.evaluation`) the final `group id`. You said something about restructuring and renaming projects?
- [ ] The person performing the release will have 
      - [ ] to setup his/her system correctly to release to sonatype ~1 day
      - [ ] set up GPG and wait for the public key to propagate ~1 day

**Comment by zesch** [comment]
At the moment, I would probably not release to Maven Central, but internally first. We already have some "customers" that would like to use a stable version in their experiments.
It would also be good to learn more about release versions.
